Use black and ruff to reformat
alanngnet/CoverHunterMPS pull request #15
Opened 2024-03-28 21:05 UTC by samuel-gauthier

First attempt at reformating the py files, using black and ruff.

2024-03-28 22:31 UTC, alanngnet approved these changes
Too many changes at once to manually review. Seems like mainly whitespace format changes. Samuel says a training launched without errors.

2024-03-29 00:53 UTC, alanngnet commented on src/module/conformer.py
> +        if isinstance(offset, int) or isinstance(offset, torch.Tensor) and offset.dim() == 0:
this doesn't seem logically equivalent, and the # scalar comment got lost.

2024-03-29 01:01 UTC, alanngnet commented on tools/eval_testset.py
> -    match hp["device"]:  # noqa match requires Python 3.10 or later
I need all the # noqa to remain as-is because of Spyder (turns off alarms for Python > 3.8)

2024-03-29 01:02 UTC, alanngnet commented on tools/train.py
> -    match hp["device"]:  # noqa requires python 3.10
leave #noqa as-is

2024-03-29 01:04 UTC, alanngnet requested changes
I liked the Black revisions, but ruff seems more annoying than helpful. I made 3 single-line comments to address before merging, otherwise the ruff changes are ok.

2024-03-29 01:09 UTC, alanngnet commented on src/dataset.py
> +        if "speed" in self._hp and random.random() <= self._hp["speed"]["prob"]:
these changes seem to introduce fragility, assuming that the hyperparameter file will have a "speed" etc. value set. It might not, and then we get an unnecessary crash, right?

2024-03-29 01:23 UTC, alanngnet commented on tools/extract_csi_features.py
> -        remake_path_for_linux(inp_path), remake_path_for_linux(out_path), k
original version is easier to read, and doesn't break line-length format rules?

2024-03-29 01:26 UTC, alanngnet requested changes
I made a few minor comments to resolve, please

2024-03-29 15:48 UTC, samuel-gauthier commented on tools/train.py
> -    match hp["device"]:  # noqa requires python 3.10
Done

2024-03-29 15:48 UTC, samuel-gauthier commented on tools/eval_testset.py
> -    match hp["device"]:  # noqa match requires Python 3.10 or later
Done

2024-03-29 15:48 UTC, samuel-gauthier commented on src/module/conformer.py
> +        if isinstance(offset, int) or isinstance(offset, torch.Tensor) and offset.dim() == 0:
Ok will remove

2024-03-29 15:49 UTC, samuel-gauthier commented on src/dataset.py
> +        if "speed" in self._hp and random.random() <= self._hp["speed"]["prob"]:
OK, I think it is removed (but not sure exactly which part you were talking about). Could you double check?

2024-03-29 15:49 UTC, samuel-gauthier commented on tools/extract_csi_features.py
> -        remake_path_for_linux(inp_path), remake_path_for_linux(out_path), k
I will revert that part manually.

2024-03-29 16:24 UTC, alanngnet approved these changes
looks good. I'm still not sold on trailing commas, but will keep an open mind. And I liked having the ".keys()" and "return"s that ruff removed, because I'm not yet fluent enough in Python for that to always be obvious to me.

2024-03-29 18:32 UTC, merged